import type { Product } from "@/data/product-types";

/** Slim product for PLP/cards — omit heavy PDP-only fields. */
export function toCardProduct(p: Product): Product {
  return {
    id: p.id,
    name: p.name,
    nameKo: p.nameKo,
    brand: p.brand,
    price: p.price,
    compareAtPrice: p.compareAtPrice,
    category: p.category,
    subcategory: p.subcategory,
    tags: p.tags,
    image: p.image,
    images: p.images?.slice(0, 8),
    hoverImage: p.hoverImage,
    accent: p.accent,
    badge: p.badge,
    sku: p.sku,
    inStock: p.inStock,
    registeredAt: p.registeredAt,
    editTier: p.editTier,
    shopColorKey: p.shopColorKey,
    cwCollections: p.cwCollections,
    ggCollections: p.ggCollections,
    variants: p.variants?.map((v) => ({
      id: v.id,
      name: v.name,
      nameKo: v.nameKo,
      sku: v.sku,
      gbpPrice: v.gbpPrice,
      price: v.price,
      compareAtPrice: v.compareAtPrice,
      image: v.image,
      images: v.images?.slice(0, 4),
      hoverImage: v.hoverImage,
      sourceUrl: v.sourceUrl,
      inStock: v.inStock,
      colorKey: v.colorKey,
      colorNameKo: v.colorNameKo,
      size: v.size,
    })),
  };
}
