/* Auto-generated by scripts/build-ce-catalog.py — do not edit */
import type { Product } from "@/data/product-types";
import data from "./ce-catalog.json";

/** Celine catalog (JSON import keeps the TS module small for Vercel builds). */
export const ceCatalogProducts = data as unknown as Product[];
