import { sitemapCount } from "@/lib/sitemap-chunks";
import { getSiteUrl } from "@/lib/site";

export const dynamic = "force-static";

/** Index of the chunked sitemaps generated by app/sitemap.ts (/sitemap/{id}.xml). */
export async function GET() {
  const site = getSiteUrl();
  const now = new Date().toISOString();
  const entries = Array.from(
    { length: sitemapCount() },
    (_, id) =>
      `  <sitemap>\n    <loc>${site}/sitemap/${id}.xml</loc>\n    <lastmod>${now}</lastmod>\n  </sitemap>`,
  ).join("\n");
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</sitemapindex>\n`;
  return new Response(xml, {
    headers: { "Content-Type": "application/xml; charset=utf-8" },
  });
}
