/* Auto-generated by scripts/build-vw-catalog.py — do not edit */
import type { Product } from "@/data/product-types";
import data from "./vw-catalog.json";

/** Vivienne Westwood catalog (JSON import keeps the TS module small for Vercel builds). */
export const vwCatalogProducts = data as unknown as Product[];
