/* Auto-generated by scripts/build-al-catalog.py — do not edit */
import type { Product } from "@/data/product-types";
import data from "./al-catalog.json";

/** AllSaints catalog (JSON import). */
export const alCatalogProducts = data as unknown as Product[];
