/* Auto-generated by scripts/build-ys-catalog.py — do not edit */
import type { Product } from "@/data/product-types";
import data from "./ys-catalog.json";

/** Saint Laurent catalog (JSON import keeps the TS module small for Vercel builds). */
export const ysCatalogProducts = data as unknown as Product[];
