MEN_DETAIL_EXTRA: dict[str, str] = {
    "-100% virgin wool": "100% 버진 울",
    "100% polyamide": "100% 폴리아미드",
    "100% silk": "100% 실크",
    "100% wool": "100% 울",
    "125 mm": "125mm",
    "130 mm": "130mm",
    "39% cashmere 39% silk 22% wool": "캐시미어 39% · 실크 39% · 울 22%",
    "50% wool 50% silk": "울 50% · 실크 50%",
    "52% cashmere 48% wool": "캐시미어 52% · 울 48%",
    "7 cm blade": "블레이드 7cm",
    "76% wool and 24% silk": "울 76% · 실크 24%",
    "925 Sterling silver": "925 스털링 실버",
    "925 sterling silver": "925 스털링 실버",
    "Acetate frame front - Black": "아세테이트 프레임 프론트 · Black",
    "Acetate frame front - Color: Iolite Horn": "아세테이트 프레임 프론트 · 컬러: Iolite Horn",
    "Acetate frame front - Color: Transparent Asphalt Gray": "아세테이트 프레임 프론트 · 컬러: Transparent Asphalt Gray",
    "Acetate frame front - Color: Transparent asphalt gray": "아세테이트 프레임 프론트 · 컬러: Transparent asphalt gray",
    "Acetate frame front - Crystal Gray": "아세테이트 프레임 프론트 · Crystal Gray",
    "Adjusted closure on the back": "뒷면 길이 조절 클로저",
    "Ambient temperature": "상온 건조",
    "Available in different sizes": "다양한 사이즈 구성",
    "Available online and at the Cortina d’Ampezzo store": "온라인 및 Cortina d’Ampezzo 스토어에서 구매 가능",
    "Belt buckle not included": "벨트 버클 미포함",
    "Belt not included": "벨트 미포함",
    "Belt strap not included": "벨트 스트랩 미포함",
    "Bio-acetate frame front - Color: Ocean Blue": "바이오 아세테이트 프레임 프론트 · 컬러: Ocean Blue",
    "Bio-acetate frame front - Color: Transparent Ocean Blue": "바이오 아세테이트 프레임 프론트 · 컬러: Transparent Ocean Blue",
    "Bio-acetate frame front - Color: Transparent brown": "바이오 아세테이트 프레임 프론트 · 컬러: Transparent brown",
    "Bio-acetate frame front - Transparent Ocean Blue": "바이오 아세테이트 프레임 프론트 · Transparent Ocean Blue",
    "Blade 5 cm": "블레이드 5cm",
    "Blade 7 cm": "블레이드 7cm",
    "Blade cm 7": "블레이드 7cm",
    "Blue Light lenses without prescription have a special filter to reduce exposure to the blue light of digital devices and sunlight.": "무도수 블루라이트 렌즈는 디지털 기기와 햇빛의 블루라이트 노출을 줄이는 특수 필터가 적용되어 있습니다.",
    "Blue Light lenses without prescription have a special filter to reduce exposure to the blue light of digital devices and sunlight. Blue light is considered harmful up to 455 nm, with peak toxicity between 415 and 455 nm.": "무도수 블루라이트 렌즈는 디지털 기기와 햇빛의 블루라이트 노출을 줄이는 특수 필터가 적용되어 있습니다. 블루라이트는 455nm까지 유해하며, 415–455nm 구간에서 독성이 가장 높습니다.",
    "Box clasp": "박스 클라스프",
    "Buckle not included": "버클 미포함",
    "Buckle with double ring": "더블 링 버클",
    "Cable-knit": "케이블 니트",
    "Cable-knit and ribbed knit": "케이블 니트 & 리브 니트",
    "Cashmere lined": "캐시미어 라이닝",
    "Cashmere lining": "캐시미어 안감",
    "Cloth triangle logo": "클로스 트라이앵글 로고",
    "Double ring buckle": "더블 링 버클",
    "Drawstring on the cuff": "커프 드로우스트링",
    "Drawstrings on the cuffs": "커프 드로우스트링",
    "Elastic tab and hook closure": "탄성 탭 & 훅 클로저",
    "Enamel triangle logo": "에나멜 트라이앵글 로고",
    "Enameled 925 sterling silver": "에나멜 925 스털링 실버",
    "Enameled metal triangle logo on the front": "앞면 에나멜 메탈 트라이앵글 로고",
    "Engraved Prada logo": "각인 Prada 로고",
    "Engraved Savoia logo": "각인 Savoia 로고",
    "Engraved lettering logo": "각인 레터링 로고",
    "Engraved logo on buckle": "버클 각인 로고",
    "Fabric triangle logo": "패브릭 트라이앵글 로고",
    "Five holes": "5홀",
    "Glass lenses": "글래스 렌즈",
    "Goatskin palm": "고트스킨 손바닥",
    "Hand-sewn": "핸드 스티치",
    "Hand-stitched": "핸드 스티치",
    "Hand-stitched hem and fringe on two sides": "양면 핸드 스티치 헴 & 프린지",
    "Heat-embossed logo": "히트 엠보스 로고",
    "Heat-sealed Linea Rossa label": "히트 실 Linea Rossa 라벨",
    "Hem plus fringe on two sides": "양면 헴 & 프린지",
    "Interior with zipper pocket": "내부 지퍼 포켓",
    "Knitted": "니트",
    "Knitted wrist": "니트 손목",
    "Leather and enameled metal triangle logo": "가죽 & 에나멜 메탈 트라이앵글 로고",
    "Leather inserts": "가죽 인서트",
    "Lens-nose-temple measurement: 136": "렌즈-브릿지-템플 길이: 136",
    "Lens-nose-temple measurement: 140": "렌즈-브릿지-템플 길이: 140",
    "Lens-nose-temple measurement: 49-24-145 mm": "렌즈-브릿지-템플 길이: 49-24-145 mm",
    "Lens-nose-temple measurement: 50-22-145 mm": "렌즈-브릿지-템플 길이: 50-22-145 mm",
    "Lens-nose-temple measurement: 51-19-145 mm": "렌즈-브릿지-템플 길이: 51-19-145 mm",
    "Lens-nose-temple measurement: 52-20-140 mm": "렌즈-브릿지-템플 길이: 52-20-140 mm",
    "Lens-nose-temple measurement: 52-23-145 mm": "렌즈-브릿지-템플 길이: 52-23-145 mm",
    "Lens-nose-temple measurement: 53-20-145 mm": "렌즈-브릿지-템플 길이: 53-20-145 mm",
    "Lens-nose-temple measurement: 54-18-140 mm": "렌즈-브릿지-템플 길이: 54-18-140 mm",
    "Lens-nose-temple measurement: 54-19-145 mm": "렌즈-브릿지-템플 길이: 54-19-145 mm",
    "Lens-nose-temple measurement: 54-20-135 mm": "렌즈-브릿지-템플 길이: 54-20-135 mm",
    "Lens-nose-temple measurement: 54-20-140 mm": "렌즈-브릿지-템플 길이: 54-20-140 mm",
    "Lens-nose-temple measurement: 54-20-145 mm": "렌즈-브릿지-템플 길이: 54-20-145 mm",
    "Lens-nose-temple measurement: 54-21-145 mm": "렌즈-브릿지-템플 길이: 54-21-145 mm",
    "Lens-nose-temple measurement: 55-19-140 mm": "렌즈-브릿지-템플 길이: 55-19-140 mm",
    "Lens-nose-temple measurement: 55-19-145 mm": "렌즈-브릿지-템플 길이: 55-19-145 mm",
    "Lens-nose-temple measurement: 56-17-145 mm": "렌즈-브릿지-템플 길이: 56-17-145 mm",
    "Lens-nose-temple measurement: 56-19-145 mm": "렌즈-브릿지-템플 길이: 56-19-145 mm",
    "Lens-nose-temple measurement: 57-17-145 mm": "렌즈-브릿지-템플 길이: 57-17-145 mm",
    "Lens-nose-temple measurement: 57-18-145 mm": "렌즈-브릿지-템플 길이: 57-18-145 mm",
    "Lens-nose-temple measurement: 59-16-145 mm": "렌즈-브릿지-템플 길이: 59-16-145 mm",
    "Lens-nose-temple measurement: 59-17-140 mm": "렌즈-브릿지-템플 길이: 59-17-140 mm",
    "Lens-nose-temple measurement: 59-17-145 mm": "렌즈-브릿지-템플 길이: 59-17-145 mm",
    "Lens-nose-temple measurement: 61-14-145 mm": "렌즈-브릿지-템플 길이: 61-14-145 mm",
    "Lens-nose-temple measurement: 61-15-145 mm": "렌즈-브릿지-템플 길이: 61-15-145 mm",
    "Lens-nose-temple measurements: 144-125 mm": "렌즈-브릿지-템플 길이: 144-125 mm",
    "Lens-nose-temple measurements: 24-124-145 mm": "렌즈-브릿지-템플 길이: 24-124-145 mm",
    "Lens-nose-temple measurements: 50-22-145 mm": "렌즈-브릿지-템플 길이: 50-22-145 mm",
    "Lens-nose-temple measurements: 52-17-145 mm": "렌즈-브릿지-템플 길이: 52-17-145 mm",
    "Lens-nose-temple measurements: 54-18-140 mm": "렌즈-브릿지-템플 길이: 54-18-140 mm",
    "Lens-nose-temple measurements: 54-19-140 mm": "렌즈-브릿지-템플 길이: 54-19-140 mm",
    "Lens-nose-temple measurements: 54-19-145 mm": "렌즈-브릿지-템플 길이: 54-19-145 mm",
    "Lens-nose-temple measurements: 54-20-140 mm": "렌즈-브릿지-템플 길이: 54-20-140 mm",
    "Lens-nose-temple measurements: 54-21-145 mm": "렌즈-브릿지-템플 길이: 54-21-145 mm",
    "Lens-nose-temple measurements: 55-18-145 mm": "렌즈-브릿지-템플 길이: 55-18-145 mm",
    "Lens-nose-temple measurements: 55-19-140 mm": "렌즈-브릿지-템플 길이: 55-19-140 mm",
    "Lens-nose-temple measurements: 57-13-140 mm": "렌즈-브릿지-템플 길이: 57-13-140 mm",
    "Lens-nose-temple measurements: 57-16-125 mm": "렌즈-브릿지-템플 길이: 57-16-125 mm",
    "Lens-nose-temple measurements: 59-15-145 mm": "렌즈-브릿지-템플 길이: 59-15-145 mm",
    "Lens-nose-temple measurements: 59-17-140 mm": "렌즈-브릿지-템플 길이: 59-17-140 mm",
    "Lens-nose-temple measurements: 60-18-120 mm": "렌즈-브릿지-템플 길이: 60-18-120 mm",
    "Line drying": "뉘어 건조",
    "Line drying in the shade": "그늘에 뉘어 건조",
    "Linen triangle logo": "린넨 트라이앵글 로고",
    "Lining with patch pocket": "패치 포켓 안감",
    "Logo engraved on the back": "뒷면 각인 로고",
    "Metal buckle covered in Saffiano leather": "Saffiano 가죽 커버 메탈 버클",
    "Metal buckle with enameled logo": "에나멜 로고 메탈 버클",
    "Metal clip closure": "메탈 클립 클로저",
    "Metal frame front - Color: Brushed Black": "메탈 프레임 프론트 · 컬러: Brushed Black",
    "Metal frame front - Color: Brushed Gold": "메탈 프레임 프론트 · 컬러: Brushed Gold",
    "Metal frame front - Color: Brushed Gunmetal Gray": "메탈 프레임 프론트 · 컬러: Brushed Gunmetal Gray",
    "Metal frame front - Color: Lead Gray": "메탈 프레임 프론트 · 컬러: Lead Gray",
    "Metal frame front - Color: Opaque Black": "메탈 프레임 프론트 · 컬러: Opaque Black",
    "Metal frame front - Color: Opaque Steel Gray": "메탈 프레임 프론트 · 컬러: Opaque Steel Gray",
    "Metal frame front - Opaque Black": "메탈 프레임 프론트 · Opaque Black",
    "Metal plaque buckle": "메탈 플라크 버클",
    "Metal triangle logo with enameled loop": "에나멜 루프 메탈 트라이앵글 로고",
    "Nylon frame front - Color: Black": "나일론 프레임 프론트 · 컬러: Black",
    "Nylon frame front - Color: Metallic Gray": "나일론 프레임 프론트 · 컬러: Metallic Gray",
    "Nylon frame front - Color: Opaque Black": "나일론 프레임 프론트 · 컬러: Opaque Black",
    "Nylon frame front - Color: Opaque White": "나일론 프레임 프론트 · 컬러: Opaque White",
    "Nylon tape strap with side-release buckle": "사이드 릴리스 버클 나일론 테이프 스트랩",
    "One side in Saffiano leather": "한 면 Saffiano 가죽",
    "One side in leather": "한 면 가죽",
    "Padded": "패딩",
    "Photochromic crystal lenses that darken in sunlight in less than a minute. After UV exposure, they gradually return to their initial state. They do not darken in artificial light.": "포토크로믹 크리스탈 렌즈는 1분 이내 햇빛 아래에서 어두워집니다. UV 노출 후 점차 원래 상태로 돌아오며, 인공 조명에서는 어두워지지 않습니다.",
    "Pile lining": "파일 안감",
    "Plaque buckle": "플라크 버클",
    "Plaque buckle with engraved logo": "각인 로고 플라크 버클",
    "Polarized Lenses": "편광 렌즈",
    "Polarized lenses": "편광 렌즈",
    "Polished steel buckle": "폴리시드 스틸 버클",
    "Pre-knotted": "프리 노트",
    "Protect leather parts during washing": "세탁 시 가죽 부분 보호",
    "Push-lock clasp": "푸시 락 클라스프",
    "Re-Nylon details": "Re-Nylon 디테일",
    "Re-Nylon logo print lining": "Re-Nylon 로고 프린트 안감",
    "Recycled bio-acetate frame front - Color: Streaked Cognac": "리사이클 바이오 아세테이트 프레임 프론트 · 컬러: Streaked Cognac",
    "Recycled bio-acetate frame front -- Color: Briarwood Tortoiseshell": "리사이클 바이오 아세테이트 프레임 프론트 · 컬러: Briarwood Tortoiseshell",
    "Reversible": "리버서블",
    "Reversible item": "리버서블",
    "Ribbed knit": "리브 니트",
    "Sartorial label": "사토리얼 라벨",
    "Sartorial logo label": "사토리얼 로고 라벨",
    "Shaker knit": "Shaker 니트",
    "Shearling and cashmere lining": "시어링 & 캐시미어 안감",
    "Shearling lining": "시어링 안감",
    "Side-release buckle": "사이드 릴리스 버클",
    "Side-release buckle clasp": "사이드 릴리스 버클 클라스프",
    "Small strap with buckle": "버클 미니 스트랩",
    "Snap button closure": "스냅 버튼 클로저",
    "Strap closure with button": "버튼 스트랩 클로저",
    "Strap not included": "스트랩 미포함",
    "Symbole mini print": "Symbole 미니 프린트",
    "T-bar clasp": "T바 클라스프",
    "The Blue Light lenses without prescription have a special filter to reduce exposure to the blue light of digital devices and sunlight. Blue light is considered harmful up to 455 nm with maximum toxicity between 415-455 nm": "무도수 블루라이트 렌즈는 디지털 기기와 햇빛의 블루라이트 노출을 줄이는 특수 필터가 적용되어 있습니다. 블루라이트는 455nm까지 유해하며, 415–455nm 구간에서 독성이 가장 높습니다.",
    "The fabric is made of regenerated yarn obtained from plastic materials collected in the ocean.": "바다에서 수거한 플라스틱 소재로 만든 재생 원사 패브릭입니다.",
    "The model is 177 cm tall and wears a size 38": "모델 키 177cm · 사이즈 38 착용",
    "The model is 186 cm tall and wears a size 48": "모델 키 186cm · 사이즈 48 착용",
    "The model is 189 cm tall and wears a size 48": "모델 키 189cm · 사이즈 48 착용",
    "Titanium frame front in black opaque titanium": "티타늄 프레임 프론트 · black opaque titanium",
    "Titanium frame front in lead gray brushed titanium": "티타늄 프레임 프론트 · lead gray brushed titanium",
    "Triangle logo on the side": "사이드 트라이앵글 로고",
    "Two-toned Saffiano leather": "투톤 Saffiano 가죽",
    "Universal fit": "유니버설 핏",
    "Visible logo": "비저블 로고",
    "Visible logo on clasp": "클라스프 비저블 로고",
    "Visible logo on triangle": "트라이앵글 비저블 로고",
    "Wash by hand": "손세탁",
    "Washed treatment": "워싱 가공",
    "With removable snap hook": "탈착식 스냅 후크",
}
