"""Burberry Children (키즈용) → Briq collection map (shared by scrape + build)."""

from __future__ import annotations

# (briq_id, label_en, plp_path, briq_top_category, parent_group)
CHILDREN_COLLECTIONS: list[tuple[str, str, str, str, str]] = [
    # Luxury — Latest
    (
        "bb-kids-new",
        "New",
        "/l/childrens-collections/new-arrivals/",
        "luxury",
        "bb-kids-latest",
    ),
    (
        "bb-kids-back-to-school",
        "Back to School",
        "/l/childrens-collections/back-to-school/",
        "luxury",
        "bb-kids-latest",
    ),
    (
        "bb-kids-summer-styles",
        "Summer Styles",
        "/l/childrens-collections/summer-styles/",
        "luxury",
        "bb-kids-latest",
    ),
    (
        "bb-kids-classics",
        "Burberry Classics",
        "/l/childrens-collections/burberry-classics/",
        "luxury",
        "bb-kids-latest",
    ),
    # Newborn (1-18 Months)
    (
        "bb-kids-newborn",
        "Newborn",
        "/l/newborn-clothes/",
        "luxury",
        "bb-kids-newborn",
    ),
    (
        "bb-kids-newborn-onesies-dresses",
        "Onesies & Dresses",
        "/l/newborn-clothes/onesies-dresses/",
        "luxury",
        "bb-kids-newborn",
    ),
    (
        "bb-kids-newborn-shoes-accessories",
        "Newborn Shoes & Accessories",
        "/l/newborn-clothes/shoes-accessories/",
        "shoes",
        "bb-kids-shoes",
    ),
    # Baby (6-36 Months)
    ("bb-kids-baby", "Baby", "/l/baby-clothes/", "luxury", "bb-kids-baby"),
    (
        "bb-kids-baby-coats-jackets",
        "Baby Coats & Jackets",
        "/l/baby-clothes/coats-jackets/",
        "luxury",
        "bb-kids-baby",
    ),
    (
        "bb-kids-baby-dresses",
        "Baby Dresses",
        "/l/baby-clothes/dresses/",
        "luxury",
        "bb-kids-baby",
    ),
    (
        "bb-kids-baby-tops",
        "Baby Tops",
        "/l/baby-clothes/tops/",
        "luxury",
        "bb-kids-baby",
    ),
    (
        "bb-kids-baby-knitwear",
        "Baby Knitwear",
        "/l/baby-clothes/knitwear/",
        "luxury",
        "bb-kids-baby",
    ),
    (
        "bb-kids-baby-skirts-trousers",
        "Baby Skirts & Trousers",
        "/l/baby-clothes/trousers-skirts/",
        "luxury",
        "bb-kids-baby",
    ),
    (
        "bb-kids-baby-swimwear",
        "Baby Swimwear",
        "/l/baby-clothes/swimwear/",
        "luxury",
        "bb-kids-baby",
    ),
    (
        "bb-kids-baby-shoes-accessories",
        "Baby Shoes & Accessories",
        "/l/baby-clothes/shoes-accessories/",
        "shoes",
        "bb-kids-shoes",
    ),
    # Girls (3-14 Years)
    ("bb-kids-girls", "Girls", "/l/girls-clothes/", "luxury", "bb-kids-girls"),
    (
        "bb-kids-girls-coats-jackets",
        "Girls Coats & Jackets",
        "/l/girls-clothes/coats-jackets/",
        "luxury",
        "bb-kids-girls",
    ),
    (
        "bb-kids-girls-dresses",
        "Dresses & Jumpsuits",
        "/l/girls-clothes/dresses/",
        "luxury",
        "bb-kids-girls",
    ),
    (
        "bb-kids-girls-tops",
        "Girls Tops",
        "/l/girls-clothes/tops-t-shirts/",
        "luxury",
        "bb-kids-girls",
    ),
    (
        "bb-kids-girls-hoodies-sweatshirts",
        "Girls Hoodies & Sweatshirts",
        "/l/girls-clothes/hoodies-sweatshirts/",
        "luxury",
        "bb-kids-girls",
    ),
    (
        "bb-kids-girls-knitwear",
        "Girls Knitwear & Cardigans",
        "/l/girls-clothes/knitwear-sweaters-cardigans/",
        "luxury",
        "bb-kids-girls",
    ),
    (
        "bb-kids-girls-skirts-trousers",
        "Girls Skirts & Trousers",
        "/l/girls-clothes/trousers-skirts/",
        "luxury",
        "bb-kids-girls",
    ),
    (
        "bb-kids-girls-swimwear",
        "Girls Swimwear",
        "/l/girls-clothes/swimwear/",
        "luxury",
        "bb-kids-girls",
    ),
    (
        "bb-kids-girls-scarves",
        "Girls’ Scarves",
        "/l/girls-clothes/scarves/",
        "accessories",
        "bb-kids-accessories",
    ),
    (
        "bb-kids-girls-shoes-accessories",
        "Girls Shoes & Accessories",
        "/l/girls-clothes/shoes-accessories/",
        "shoes",
        "bb-kids-shoes",
    ),
    # Boys (3-14 Years)
    ("bb-kids-boys", "Boys", "/l/boys-clothes/", "luxury", "bb-kids-boys"),
    (
        "bb-kids-boys-coats-jackets",
        "Boys Coats & Jackets",
        "/l/boys-clothes/coats-jackets/",
        "luxury",
        "bb-kids-boys",
    ),
    (
        "bb-kids-boys-polos-tshirts",
        "Boys Polos & T-shirts",
        "/l/boys-clothes/polos-t-shirts/",
        "luxury",
        "bb-kids-boys",
    ),
    (
        "bb-kids-boys-shirts",
        "Boys Shirts",
        "/l/boys-clothes/shirts/",
        "luxury",
        "bb-kids-boys",
    ),
    (
        "bb-kids-boys-knitwear",
        "Boys Knitwear & Cardigans",
        "/l/boys-clothes/knitwear-sweaters-cardigans/",
        "luxury",
        "bb-kids-boys",
    ),
    (
        "bb-kids-boys-hoodies-sweatshirts",
        "Boys Hoodies & Sweatshirts",
        "/l/boys-clothes/hoodies-sweatshirts/",
        "luxury",
        "bb-kids-boys",
    ),
    (
        "bb-kids-boys-trousers-shorts",
        "Boys Trousers & Shorts",
        "/l/boys-clothes/trousers-shorts/",
        "luxury",
        "bb-kids-boys",
    ),
    (
        "bb-kids-boys-swimwear",
        "Boys Swimwear",
        "/l/boys-clothes/swimwear/",
        "luxury",
        "bb-kids-boys",
    ),
    (
        "bb-kids-boys-scarves",
        "Boys’ Scarves",
        "/l/boys-clothes/scarves/",
        "accessories",
        "bb-kids-accessories",
    ),
    (
        "bb-kids-boys-shoes-accessories",
        "Boys Shoes & Accessories",
        "/l/boys-clothes/shoes-accessories/",
        "shoes",
        "bb-kids-shoes",
    ),
    # Bags
    (
        "bb-kids-bags",
        "Bags",
        "/l/childrens-accessories/bags/",
        "bags",
        "bb-kids-bags",
    ),
    # Accessories
    (
        "bb-kids-hats-socks",
        "Hats & Socks",
        "/l/childrens-accessories/hats-socks/",
        "accessories",
        "bb-kids-accessories",
    ),
    (
        "bb-kids-hair-accessories",
        "Hair Accessories",
        "/l/childrens-accessories/hair-accessories/",
        "accessories",
        "bb-kids-accessories",
    ),
    (
        "bb-kids-scarves",
        "Scarves",
        "/l/childrens-accessories/scarves/",
        "accessories",
        "bb-kids-accessories",
    ),
    # Gifts
    (
        "bb-kids-gifts",
        "Gifts",
        "/l/childrens-gifts/",
        "accessories",
        "bb-kids-gifts",
    ),
    (
        "bb-kids-gift-girls-scarves",
        "Girls’ Scarves",
        "/l/girls-clothes/scarves/",
        "accessories",
        "bb-kids-gifts",
    ),
    (
        "bb-kids-gift-boys-scarves",
        "Boys’ Scarves",
        "/l/boys-clothes/scarves/",
        "accessories",
        "bb-kids-gifts",
    ),
    (
        "bb-kids-newborn-gifts",
        "Newborn Gifts",
        "/l/childrens-gifts/newborn/",
        "accessories",
        "bb-kids-gifts",
    ),
    (
        "bb-kids-newborn-gift-sets",
        "Gift Sets",
        "/l/childrens-gifts/newborn/gift-sets/",
        "accessories",
        "bb-kids-gifts",
    ),
    (
        "bb-kids-baby-gifts",
        "Baby Gifts",
        "/l/childrens-gifts/baby-gifts/",
        "accessories",
        "bb-kids-gifts",
    ),
]
