"""Burberry Men → Briq collection map (shared by scrape + build)."""

from __future__ import annotations

# (briq_id, label_en, plp_path, briq_top_category, parent_group)
MEN_COLLECTIONS: list[tuple[str, str, str, str, str]] = [
    # Luxury — Latest
    ("bb-men-new", "New", "/l/mens-clothing/new-arrivals/", "luxury", "bb-men-latest"),
    (
        "bb-men-summer-styles",
        "Summer Styles",
        "/l/mens-clothing/summer-styles/",
        "luxury",
        "bb-men-latest",
    ),
    (
        "bb-men-classics",
        "Burberry Classics",
        "/l/mens-clothing/classics/",
        "luxury",
        "bb-men-latest",
    ),
    # Luxury — Coats & Jackets
    (
        "bb-men-coats-jackets",
        "Coats & Jackets",
        "/l/mens-coats-jackets/",
        "luxury",
        "bb-men-coats-jackets",
    ),
    ("bb-men-coats", "Coats", "/l/mens-coats-jackets/coats/", "luxury", "bb-men-coats-jackets"),
    (
        "bb-men-jackets",
        "Jackets",
        "/l/mens-coats-jackets/jackets/",
        "luxury",
        "bb-men-coats-jackets",
    ),
    (
        "bb-men-trench-coats",
        "Trench Coats",
        "/l/mens-coats-jackets/trench-coats/",
        "luxury",
        "bb-men-coats-jackets",
    ),
    (
        "bb-men-quilted-jackets",
        "Quilted Jackets",
        "/l/mens-coats-jackets/quilts/",
        "luxury",
        "bb-men-coats-jackets",
    ),
    (
        "bb-men-puffer-jackets",
        "Puffer Jackets",
        "/l/mens-coats-jackets/puffers/",
        "luxury",
        "bb-men-coats-jackets",
    ),
    # Luxury — Clothes
    ("bb-men-clothes", "Clothes", "/l/mens-clothing/", "luxury", "bb-men-clothes"),
    (
        "bb-men-knitwear",
        "Knitwear",
        "/l/mens-clothing/knitwear/",
        "luxury",
        "bb-men-clothes",
    ),
    (
        "bb-men-polos",
        "Polos",
        "/l/mens-clothing/polos-t-shirts/polos/",
        "luxury",
        "bb-men-clothes",
    ),
    (
        "bb-men-tshirts",
        "T-shirts",
        "/l/mens-clothing/polos-t-shirts/t-shirts/",
        "luxury",
        "bb-men-clothes",
    ),
    (
        "bb-men-shirts",
        "Shirts",
        "/l/mens-clothing/shirts/",
        "luxury",
        "bb-men-clothes",
    ),
    (
        "bb-men-hoodies-sweatshirts",
        "Hoodies & Sweatshirts",
        "/l/mens-clothing/hoodies-sweatshirts/",
        "luxury",
        "bb-men-clothes",
    ),
    (
        "bb-men-blazers-tailoring",
        "Blazers & Tailoring",
        "/l/mens-clothing/blazers-tailored-trousers/",
        "luxury",
        "bb-men-clothes",
    ),
    (
        "bb-men-trousers-shorts",
        "Trousers & Shorts",
        "/l/mens-clothing/trousers-shorts/",
        "luxury",
        "bb-men-clothes",
    ),
    (
        "bb-men-activewear",
        "Activewear",
        "/l/mens-clothing/activewear/",
        "luxury",
        "bb-men-clothes",
    ),
    ("bb-men-denim", "Denim", "/l/mens-clothing/denim/", "luxury", "bb-men-clothes"),
    (
        "bb-men-swimwear",
        "Swimwear",
        "/l/mens-clothing/swimwear/",
        "luxury",
        "bb-men-clothes",
    ),
    # Bags
    ("bb-men-bags", "Bags", "/l/mens-bags/", "bags", "bb-men-bags"),
    (
        "bb-men-crossbody-bags",
        "Crossbody Bags",
        "/l/mens-bags/crossbody/",
        "bags",
        "bb-men-bags",
    ),
    ("bb-men-backpacks", "Backpacks", "/l/mens-bags/backpacks/", "bags", "bb-men-bags"),
    ("bb-men-belt-bags", "Belt Bags", "/l/mens-bags/belt-bags/", "bags", "bb-men-bags"),
    ("bb-men-tote-bags", "Tote Bags", "/l/mens-bags/tote/", "bags", "bb-men-bags"),
    ("bb-men-holdall-bags", "Holdall Bags", "/l/mens-bags/holdalls/", "bags", "bb-men-bags"),
    (
        "bb-men-briefcases",
        "Briefcases",
        "/l/mens-bags/briefcases/",
        "bags",
        "bb-men-bags",
    ),
    # Shoes
    ("bb-men-shoes", "Shoes", "/l/mens-shoes/", "shoes", "bb-men-shoes"),
    ("bb-men-sneakers", "Sneakers", "/l/mens-shoes/sneakers/", "shoes", "bb-men-shoes"),
    ("bb-men-sandals", "Sandals", "/l/mens-shoes/sandals/", "shoes", "bb-men-shoes"),
    ("bb-men-boots", "Boots", "/l/mens-shoes/boots/", "shoes", "bb-men-shoes"),
    (
        "bb-men-loafers-lace-ups",
        "Loafers & Lace-ups",
        "/l/mens-shoes/loafers-lace-up/",
        "shoes",
        "bb-men-shoes",
    ),
    # Accessories (no parent PLP — /l/mens-accessories/ redirects to hub without product grid)
    (
        "bb-men-scarves",
        "Scarves",
        "/l/mens-accessories/scarves/",
        "accessories",
        "bb-men-accessories",
    ),
    (
        "bb-men-ties-cufflinks",
        "Ties & Cufflinks",
        "/l/mens-accessories/ties-cufflinks/",
        "accessories",
        "bb-men-accessories",
    ),
    (
        "bb-men-belts",
        "Belts",
        "/l/mens-accessories/belts/",
        "accessories",
        "bb-men-accessories",
    ),
    (
        "bb-men-sunglasses",
        "Sunglasses",
        "/l/mens-accessories/sunglasses/",
        "accessories",
        "bb-men-accessories",
    ),
    (
        "bb-men-caps-hats",
        "Caps & Bucket Hats",
        "/l/mens-accessories/hats-gloves/",
        "accessories",
        "bb-men-accessories",
    ),
    ("bb-men-umbrellas", "Umbrellas", "/l/umbrellas/", "accessories", "bb-men-accessories"),
    (
        "bb-men-jewellery",
        "Jewellery",
        "/l/mens-accessories/jewellery/",
        "accessories",
        "bb-men-accessories",
    ),
    (
        "bb-men-socks",
        "Socks",
        "/l/mens-accessories/socks/",
        "accessories",
        "bb-men-accessories",
    ),
    (
        "bb-men-tech-travel",
        "Tech & Travel",
        "/l/mens-accessories/tech-travel/",
        "accessories",
        "bb-men-accessories",
    ),
    (
        "bb-men-home",
        "Home",
        "/l/home-accessories/",
        "accessories",
        "bb-men-accessories",
    ),
    (
        "bb-men-key-charms",
        "Key & Bag Charms",
        "/l/mens-accessories/key-rings/",
        "accessories",
        "bb-men-accessories",
    ),
    # Wallets
    (
        "bb-men-wallets",
        "Wallets & Card Cases",
        "/l/mens-accessories/wallets-card-cases/",
        "accessories",
        "bb-men-wallets",
    ),
    (
        "bb-men-bifold-wallets",
        "Bifold Wallets",
        "/l/mens-accessories/wallets-card-cases/benefit=bifold_wallets/",
        "accessories",
        "bb-men-wallets",
    ),
    (
        "bb-men-card-cases",
        "Card Cases",
        "/l/mens-accessories/wallets-card-cases/benefit=card_cases/",
        "accessories",
        "bb-men-wallets",
    ),
    (
        "bb-men-long-wallets",
        "Long Wallets",
        "/l/mens-accessories/wallets-card-cases/benefit=long_wallets/",
        "accessories",
        "bb-men-wallets",
    ),
    (
        "bb-men-pouches",
        "Pouches",
        "/l/mens-accessories/pouches/",
        "accessories",
        "bb-men-wallets",
    ),
    # Gifts
    ("bb-men-gifts", "Gifts", "/l/mens-gifts/", "accessories", "bb-men-gifts"),
    (
        "bb-men-fragrance",
        "Fragrance",
        "/l/mens-fragrances/",
        "accessories",
        "bb-men-gifts",
    ),
    (
        "bb-men-personalised-gifts",
        "Personalised Gifts",
        "/l/mens-gifts/personalised/",
        "accessories",
        "bb-men-gifts",
    ),
    (
        "bb-men-personalised-scarves",
        "Personalised Scarves",
        "/l/mens-accessories/scarves/personalised/",
        "accessories",
        "bb-men-gifts",
    ),
]
