#!/usr/bin/env python3
"""Offline Celine PDP prose EN→KO (no TITLE_MAP hybrids, no remote required)."""
from __future__ import annotations

import re
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from ko_qa import is_good_korean  # noqa: E402

# Exact / near-exact care + fit lines (normalized keys: lower, hyphen→space, collapse ws, strip .).
CARE_FIT_MAP: dict[str, str] = {
    "the item can be washed on a delicate cycle at a maximum temperature of 30°c / 85°f": "최대 30°C의 섬세 코스로 세탁해 주세요.",
    "the item can be hand washed in water at a maximum temperature of 30°c / 85°f": "최대 30°C 물로 손세탁해 주세요.",
    "the item can be hand-washed in water at a maximum temperature of 30°c / 85°f": "최대 30°C 물로 손세탁해 주세요.",
    "only use bleach free laundry products": "표백 성분이 없는 세제를 사용해 주세요.",
    "only use bleach-free laundry products": "표백 성분이 없는 세제를 사용해 주세요.",
    "do not tumble dry": "건조기 사용은 권장되지 않습니다.",
    "line dry without spin": "탈수 없이 평평하게 건조해 주세요.",
    "line dry": "평평하게 건조해 주세요.",
    "maximum ironing temperature: 110°c / 230°f": "최대 다림질 온도: 110°C/230°F",
    "maximum ironing temperature: 150°c / 302°f": "다림질 최대 온도는 150°C입니다.",
    "iron at a maximum of 200°c/230°f": "최대 200°C까지 다림질할 수 있습니다.",
    "do not use steam": "스팀을 사용하지 마십시오.",
    "the item can be delicately dry cleaned with hydrocarbons": "하이드로카본 계열로 약하게 드라이클리닝할 수 있습니다.",
    "the item can be delicately dry cleaned with hydrocarbons or tetrachloroethylene": "하이드로카본 또는 테트라클로로에틸렌으로 약하게 드라이클리닝할 수 있습니다.",
    "do not dry clean": "드라이클리닝하지 마십시오.",
    "do not professionally clean with water": "물세탁 전문 클리닝은 하지 마십시오.",
    "do not wash with water": "물로 씻지 마십시오.",
    "do not iron": "다림질하지 마십시오.",
    "the loose celine shape is a large fit with dropped shoulders": "느슨한 셀린느 실루엣은 드롭 숄더의 여유 있는 핏입니다.",
    "the loose celine shape is a large fit": "느슨한 셀린느 실루엣은 여유 있는 핏입니다.",
    "the oversized celine shape is an extra large fit with dropped shoulders and a loose body": "오버사이즈 셀린느 실루엣은 드롭 숄더와 여유 있는 바디의 엑스트라 라지 핏입니다.",
    "it is possible to take one size down from your usual size for a more fitted look": "평소 사이즈보다 한 사이즈 아래로 선택하면 더 몸에 꼭 맞는 룩을 연출할 수 있습니다.",
    "it is possible to size down": "한 사이즈 작게 선택하는 것도 가능합니다.",
    "the classic celine shape fits true to size": "셀린느의 클래식 실루엣 기준 정사이즈로 제안됩니다.",
    "the classic celine shape is fitted to the body": "셀린느의 클래식 실루엣은 바디에 맞게 제작됩니다.",
    "the classic celine t shirt is fitted to the body. we suggest taking your usual size": "셀린느 클래식 티셔츠는 바디에 맞게 제작됩니다. 평소 선택하시는 사이즈를 권장합니다.",
    "the classic celine shape fits true to size. we suggest taking your usual size": "셀린느의 클래식 실루엣 기준 정사이즈로 제안됩니다. 평소 선택하시는 사이즈를 권장합니다.",
    "we suggest taking your usual size": "평소 선택하시는 사이즈를 권장합니다.",
    "fits true to size": "정사이즈로 제안됩니다.",
    # Long care guides (summarized, natural KO)
    "for your shoes, celine has selected the highest quality hides": (
        "셀린느는 슈즈에 최고급 가죽을 사용합니다. 색감 차이·작은 자국·결은 자연스러운 특성입니다. "
        "물·기름·향수·화장품 접촉을 피하고, 젖은 경우 부드러운 밝은색 천으로 닦아 주세요. "
        "강한 열·직사광선을 피하고, 굽·밑창 마모 시 전문점에 의뢰하세요. 미착용 시 파우치와 박스에 보관하세요."
    ),
    "your celine belt was crafted using the most luxurious skins": (
        "셀린느 벨트는 고급 가죽으로 제작됩니다. 톤 차이·자국·결은 자연스러운 특성입니다. "
        "물·오일·향수·화장품 접촉을 피하고, 거친 마찰을 피하세요. 펠트 보관백에 보관하고 플라스틱 백·고온·다습·밀폐 공간은 피하세요."
    ),
    "celine leather goods are crafted in the most luxurious skins": (
        "셀린느 레더 굿즈는 고급 가죽으로 제작됩니다. 톤 차이·자국·결은 자연스러운 특성입니다. "
        "습기를 피하고 물·핸드크림·손소독제·메이크업·향수 접촉을 피하세요. 거친 마찰을 피하고 더스트백에 보관하세요."
    ),
    "celine created high end and refined jewels with timeless materials": (
        "셀린느 주얼리는 고급 소재로 제작됩니다. 부드러운 천으로 닦아 주세요. "
        "미착용 시 셀린느 파우치에 보관하고, 단단한 브레이슬릿의 무리한 휨·바닷물·강한 화학 물질 접촉을 피하세요. 니켈 프리·저자극성입니다."
    ),
    "celine has selected materials of the highest quality to create your sunglasses": (
        "셀린느 선글라스는 고급 소재로 제작됩니다. 용제·강한 세제는 사용하지 마시고, "
        "미지근한 물과 중성 비누로 닦은 뒤 부드러운 천으로 건조하세요. 케이스에 -10°C~+35°C의 건조한 곳에 보관하세요."
    ),
    "avoid contact with water, oil, perfume and cosmetic products": "물·오일·향수·화장품 접촉을 피하세요.",
    "avoid overexposure to heat and intense light": "강한 열과 직사광선에 오래 노출되지 않게 하세요.",
    "to make sure your belt ages beautifully, we recommend that you": "벨트가 아름답게 에이징되도록 아래를 권장합니다.",
    "be careful not to rub your belt against coarse or abrasive surfaces. light scratches can be diminished if gently massaged with a soft, dry cloth": "거친·마모성 표면에 벨트가 마찰되지 않게 하세요. 가벼운 스크래치는 부드럽고 마른 천으로 살살 문지르면 완화될 수 있습니다.",
    "store it in its protective felt bag. do not store at a high temperature, humidity level or in an unventilated area. never store it in a plastic bag": "보호용 펠트백에 보관하세요. 고온·다습·밀폐 공간·플라스틱 백 보관은 피하세요.",
    "avoid contact with water, grease, perfume and cosmetics. dry damp shoes with a soft, light coloured cloth to absorb any liquid": "물·기름·향수·화장품 접촉을 피하고, 젖은 슈즈는 부드러운 밝은색 천으로 닦아 주세요.",
    "avoid prolonged exposure to heat and strong sources of light. scratches on some leathers can be reduced with gentle rubbing": "강한 열·직사광선에 오래 두지 마세요. 일부 가죽의 스크래치는 살살 문지르면 완화될 수 있습니다.",
    "if your heels or soles have worn out, take your shoes to a specialist who can reheel them or add thin rubber soles": "굽·밑창이 닳으면 전문점에서 힐 교체나 얇은 러버 솔 추가를 의뢰하세요.",
    "when you are not wearing your shoes, we recommend storing them in their individual pouches inside the box": "미착용 시 개별 파우치와 박스에 보관하세요.",
    "to clean your shoes, wipe them carefully using a clean, soft cloth that is left dry for leather or slightly moistened for fabric": "슈즈는 깨끗한 부드러운 천으로 닦으세요. 레더는 마른 천, 패브릭은 약간 적신 천을 사용합니다.",
    "store it in the celine dust bag. do not store in high temperature, humidity or unventilated areas (never store in a plastic bag)": "셀린느 더스트백에 보관하세요. 고온·다습·밀폐 공간·플라스틱 백 보관은 피하세요.",
    "be careful not to rub your bag against coarse or abrasive surfaces. light scratches can attenuate if gently massaged with a soft, dry cloth": "거친·마모성 표면에 백이 마찰되지 않게 하세요. 가벼운 스크래치는 부드럽고 마른 천으로 살살 문지르면 완화될 수 있습니다.",
    "protect it from humidity; avoid contact with liquid, hand cream, hand sanitizer, make up and perfume. if your bag does come into contact with water or any of those substances, it should be gently dabbed with a dry, non fluffy, light coloured absorbent cloth": "습기를 피하고 액체·핸드크림·손소독제·메이크업·향수 접촉을 피하세요. 묻으면 보풀 없는 밝은색 흡수 천으로 톡톡 두드려 주세요.",
    "do not use solvents (alcohol, acetone, etc.) or aggressive detergents that may alter their features": "알코올·아세톤 등 용제나 강한 세제는 사용하지 마세요.",
    "use a damp cloth and mild soap to clean your sunglasses, then dry them with a soft, clean cloth": "미지근한 물과 중성 비누로 선글라스를 닦은 뒤 부드러운 천으로 건조하세요.",
    "store your sunglasses in their case, in a dry place, at a temperature between 10°c and +35°c": "선글라스는 케이스에 넣어 건조한 곳(-10°C~+35°C)에 보관하세요.",
    "store your sunglasses in their case, in a dry place, at a temperature between -10°c and +35°c": "선글라스는 케이스에 넣어 건조한 곳(-10°C~+35°C)에 보관하세요.",
    "avoid over exposure to direct lighting and keep it away from direct sources of heat": "직사광선·열원에서 멀리 보관하세요.",
}
# Multi-word phrases first (applied longest-first with word boundaries).
PROSE_PHRASES: dict[str, str] = {
    "mother of pearl": "자개",
    "mother-of-pearl": "자개",
    "mother on pearl": "자개",
    "hook and eye": "훅앤아이",
    "hook-and-eye": "훅앤아이",
    "side pockets": "사이드 포켓",
    "side pocket": "사이드 포켓",
    "back pocket": "백 포켓",
    "back pockets": "백 포켓",
    "patch pocket": "패치 포켓",
    "patch pockets": "패치 포켓",
    "welt pocket": "웰트 포켓",
    "welt pockets": "웰트 포켓",
    "flap pocket": "플랩 포켓",
    "zip pocket": "지퍼 포켓",
    "interior pocket": "인테리어 포켓",
    "inner pocket": "이너 포켓",
    "kangaroo pocket": "캥거루 포켓",
    "raw hems": "로우 헴",
    "raw hem": "로우 헴",
    "mid rise": "미드 라이즈",
    "high rise": "하이 라이즈",
    "low rise": "로우 라이즈",
    "high waisted": "하이웨이스트",
    "middle waist": "미들 웨이스트",
    "loose fit": "루즈 핏",
    "classic fit": "클래식 핏",
    "regular fit": "레귤러 핏",
    "oversized fit": "오버사이즈 핏",
    "adjusted fit": "핏티드 핏",
    "straight leg": "스트레이트 레그",
    "wide leg": "와이드 레그",
    "flare leg": "플레어 레그",
    "slim leg": "슬림 레그",
    "barrel leg": "배럴 레그",
    "cuffed hems": "커프드 헴",
    "cuffed hem": "커프드 헴",
    "dropped shoulders": "드롭 숄더",
    "elasticated waistband": "엘라스틱 웨이스트밴드",
    "elasticated waistline": "엘라스틱 웨이스트라인",
    "adjustable drawstrings": "조절 가능한 드로스트링",
    "adjustable drawstring": "조절 가능한 드로스트링",
    "metal aglets": "메탈 애글리트",
    "made in italy": "이탈리아 제작",
    "italy made": "이탈리아 제작",
    "made in portugal": "포르투갈 제작",
    "portugal made": "포르투갈 제작",
    "made in france": "프랑스 제작",
    "france made": "프랑스 제작",
    "made in japan": "일본 제작",
    "japan made": "일본 제작",
    "made in sweden": "스웨덴 제작",
    "sweden made": "스웨덴 제작",
    "made in united kingdom": "영국 제작",
    "made in the united kingdom": "영국 제작",
    "made in uk": "영국 제작",
    "united kingdom": "영국",
    "middle waist": "미들 웨이스트",
    "triomphe metal ring around the first loop": "첫 루프를 감싸는 트리옹프 메탈 링",
    "celine paris logo engraved on the bottom of the first loop": "첫 루프 하단에 각인된 셀린느 파리 로고",
    "removable celine disc buckle": "탈부착 셀린느 디스크 버클",
    "squared buckle": "스퀘어 버클",
    "rectangular buckle": "사각 버클",
    "western buckle": "웨스턴 버클",
    "long framed buckle": "롱 프레임 버클",
    "old silver finishing": "올드 실버 마감",
    "old gold finishing": "올드 골드 마감",
    "two metal loops and one metal tip": "메탈 루프 2개, 메탈 팁 1개",
    "hand rolled hem": "핸드롤 헴",
    "fringe edge": "프린지 엣지",
    "hexagonal design": "헥사곤 디자인",
    "harry's bar print": "Harry's bar 프린트",
    "reversible strap": "리버시블 스트랩",
    "reversible srap": "리버시블 스트랩",
    "triomphe helium buckle with collar stud": "칼라 스터드가 있는 트리옹프 헬륨 버클",
    "calfskin lining": "카프스킨 안감",
    "shirt collar": "셔츠 칼라",
    "notch collar": "노치 칼라",
    "peak collar": "피크 칼라",
    "shoulder carry": "숄더 캐리",
    "cross body carry": "크로스바디 캐리",
    "cross-body carry": "크로스바디 캐리",
    "one main compartment": "메인 수납공간 1개",
    "gold finishing": "골드 마감",
    "silver finishing": "실버 마감",
    "textile with triomphe print lining": "트리옹프 프린트 텍스타일 안감",
    "evening bag & clutches": "이브닝 백 & 클러치",
    "evening bag and clutches": "이브닝 백 & 클러치",
    "removable and adjustable strap": "탈부착·조절 가능 스트랩",
    "lambskin": "램스킨",
    "crew neck": "크루넥",
    "v neck": "브이넥",
    "raglan sleeves": "래글런 소매",
    "buttoned cuffs": "버튼 커프스",
    "snap buttons": "스냅 버튼",
    "snap button": "스냅 버튼",
    "horn buttons": "혼 버튼",
    "horn button": "혼 버튼",
    "jeans buttons": "진 버튼",
    "zip closure": "지퍼 클로저",
    "zipper closure": "지퍼 클로저",
    "hook eye closure": "훅앤아이 클로저",
    "cross body": "크로스바디",
    "cross-body": "크로스바디",
    "hand carry": "핸드 캐리",
    "elbow carry": "엘보 캐리",
    "shoulder carry": "숄더 캐리",
    "rounded buckle": "라운드 버클",
    "leather handles": "레더 핸들",
    "leather handle": "레더 핸들",
    "leather piping": "레더 파이핑",
    "adjustable strap": "조절 스트랩",
    "removable": "탈부착",
    "triomphe embroidery": "트리옹프 자수",
    "celine embroidery": "셀린느 자수",
    "celine paris": "셀린느 파리",
    "engraved metal": "각인 메탈",
    "paris engraved": "파리 각인",
    "celine engraved": "셀린느 각인",
    "triomphe engraved": "트리옹프 각인",
    "secondary material": "보조 소재",
    "maxi length": "맥시 기장",
    "midi length": "미디 기장",
    "mini length": "미니 기장",
    "asymetrical midi length hem": "비대칭 미디 기장 헴",
    "collarless jacket": "칼라리스 재킷",
    "satin covered": "새틴 커버",
    "fabric covered": "패브릭 커버",
    "leather covered": "레더 커버",
    "adjustment tabs": "조절 탭",
    "adjustement tabs": "조절 탭",
    "pull tabs": "풀 탭",
    "zip puller": "지퍼 풀러",
    "side bands": "사이드 밴드",
    "rib trim": "립 트림",
    "ribbed trim": "립 트림",
    "tonal leather welt": "톤온톤 레더 웰트",
    "rubber lug outsole": "러버 러그 아웃솔",
    "card slots": "카드 슬롯",
    "credit card": "신용카드",
    "dust bag": "더스트백",
    "felt bag": "펠트백",
    "line dry without spin": "탈수 없이 평평하게 건조해 주세요",
    "do not tumble dry": "건조기 사용은 권장되지 않습니다",
    "do not use steam": "스팀을 사용하지 마십시오",
    "do not wash with water": "물로 씻지 마십시오",
    "bleach free": "표백 성분 없는",
    "dry clean": "드라이클리닝",
    "hand washed": "손세탁",
    "hand wash": "손세탁",
    "dropped shoulders": "드롭 숄더",
    "true to size": "정사이즈",
    "usual size": "평소 사이즈",
    "fitted look": "핏티드 룩",
    "large fit": "여유 핏",
    "extra large fit": "엑스트라 라지 핏",
    "loose body": "여유 있는 바디",
    "one size down": "한 사이즈 다운",
    "size down": "사이즈 다운",
    "magnetic closure": "마그네틱 클로저",
    "magnetic": "마그네틱",
    "inside card pockets": "내부 카드 포켓",
    "double zipped closure": "더블 지퍼 클로저",
    "second material": "보조 소재",
    "washed effect": "워시드 효과",
    "ripped detailing": "립 디테일",
    "sulky embroidery": "설키 자수",
    "bay leaf embroidery": "월계수 자수",
    "bay leaf": "월계수",
    "initial patch": "이니셜 패치",
    "smooth lambskin": "스무스 램스킨",
    "deerskin": "디어스킨",
    "coton": "면",
    "laundry products": "세제",
    "bleach free laundry products": "표백 성분 없는 세제",
    "only use bleach free laundry products": "표백 성분이 없는 세제를 사용해 주세요",
    "do not iron": "다림질하지 마십시오",
    "flap with triomphe magnetic closure": "트리옹프 마그네틱 클로저 플랩",
    "flap with magnetic closure": "마그네틱 클로저 플랩",
    "removable charm": "탈부착 참",
    "asjustable design": "조절 디자인",
    "adjustable design": "조절 디자인",
    "calèche": "칼레슈",
    "caleche": "칼레슈",
    "just tell the taxi driver": "Just tell the taxi driver",
    "drugstore collar": "드럭스토어 칼라",
    "claudine collar": "클로딘 칼라",
    "mock neck": "목넥",
    "carriage logo": "캐리지 로고",
    "slingback": "슬링백",
    "slightly padded": "약하게 패딩",
    "conic leather covered heel": "코니컬 레더 커버 힐",
    "key holder": "키 홀더",
    "leather ties": "레더 타이",
    "bevel cut": "베벨 컷",
    "collar stays": "카라 스테이",
    "celine 3 dots on right temple, paris 3 dots on left temple": "오른쪽 템플 셀린느 3닷, 왼쪽 템플 파리 3닷",
    "ring width": "링 너비",
    "two leather handles": "레더 핸들 2개",
    "shoulder carry": "숄더 캐리",
    "hand carry": "핸드 캐리",
    "crew neck": "크루넥",
    "protects uva uvb": "UVA/UVB 차단",
    "temple length": "템플 기장",
    "nose bridge width": "노즈 브릿지 너비",
    "lens width": "렌즈 너비",
    "round toe shape": "라운드 토",
    "almond toe shape": "아몬드 토",
    "pointed toe shape": "포인티드 토",
    "note pocket": "노트 포켓",
    "smoke lenses": "스모크 렌즈",
    "smoke lens": "스모크 렌즈",
    "brown lenses": "브라운 렌즈",
    "cat eye frame": "캣아이 프레임",
    "cat eye": "캣아이",
    "stacked leather heel": "스택드 레더 힐",
    "pierced ears": "피어싱용",
    "turn lock closure": "턴락 클로저",
    "turn lock": "턴락",
    "polo collar": "폴로 칼라",
    "folded coin pocket": "폴디드 코인 포켓",
    "coin pocket": "코인 포켓",
    "coin purse": "코인 퍼스",
    "sliding knots system": "슬라이딩 노트 시스템",
    "gold eyelets": "골드 아일렛",
    "internal memory foam": "내부 메모리폼",
    "greater comfort": "착용감 향상",
    "better support": "지지력 향상",
    "elastic back": "엘라스틱 백",
    "perforated upper": "퍼포레이션 갑피",
    "slim perforations": "슬림 퍼포레이션",
    "flexible outsole": "플렉서블 아웃솔",
    "metallic hinge closure": "메탈릭 힌지 클로저",
    "brass crystals": "브라스 크리스탈",
    "brass resin": "브라스 레진",
    "tailored front panel": "테일러드 프론트 패널",
    "shoulder pad": "숄더 패드",
    "chest pocket": "체스트 포켓",
    "single earring": "싱글 이어링",
    "removable triomphe accessory": "탈부착 트리옹프 액세서리",
    "100% bullskin": "100% 불스킨",
    "elastic upper": "엘라스틱 갑피",
    "100% cotton": "100% 면",
    "100% wool": "100% 울",
    "100% cashmere": "100% 캐시미어",
    "100% silk": "100% 실크",
    "100% lambskin": "100% 램스킨",
    "100% calfskin": "100% 카프스킨",
    "100% polyester": "100% 폴리에스터",
    "100% polyamide": "100% 폴리아미드",
    "100% viscose": "100% 비스코스",
    "100% virgin wool": "100% 버진 울",
}

PROSE_WORDS: dict[str, str] = {
    "celine": "셀린느",
    "triomphe": "트리옹프",
    "vivienne": "비비안",
    "cotton": "면",
    "wool": "울",
    "cashmere": "캐시미어",
    "silk": "실크",
    "viscose": "비스코스",
    "polyamide": "폴리아미드",
    "polyester": "폴리에스터",
    "polyurethane": "폴리우레탄",
    "elastane": "엘라스테인",
    "acetate": "아세테이트",
    "acrylic": "아크릴",
    "nylon": "나일론",
    "modal": "모달",
    "cupro": "큐프로",
    "linen": "린넨",
    "mohair": "모헤어",
    "raffia": "라피아",
    "velvet": "벨벳",
    "satin": "새틴",
    "leather": "레더",
    "leathers": "레더",
    "calfskin": "카프스킨",
    "lambskin": "램스킨",
    "goatskin": "고트스킨",
    "sheepskin": "쉽스킨",
    "shearling": "시어링",
    "suede": "스웨이드",
    "taurillon": "토리용",
    "canvas": "캔버스",
    "textile": "텍스타일",
    "fabric": "패브릭",
    "lining": "안감",
    "unlined": "안감 없음",
    "embroidery": "자수",
    "embroidered": "자수",
    "embroideries": "자수",
    "print": "프린트",
    "printed": "프린트",
    "jacquard": "자카드",
    "patch": "패치",
    "logo": "로고",
    "logos": "로고",
    "signature": "시그니처",
    "engraved": "각인",
    "embossed": "엠보스",
    "debossed": "디보스",
    "metal": "메탈",
    "metallic": "메탈릭",
    "brass": "브라스",
    "gold": "골드",
    "silver": "실버",
    "steel": "스틸",
    "enamel": "에나멜",
    "pearl": "펄",
    "diamond": "다이아몬드",
    "diamonds": "다이아몬드",
    "strass": "스트라스",
    "buckle": "버클",
    "belt": "벨트",
    "strap": "스트랩",
    "straps": "스트랩",
    "handle": "핸들",
    "handles": "핸들",
    "chain": "체인",
    "chains": "체인",
    "ring": "링",
    "loops": "루프",
    "loop": "루프",
    "tab": "탭",
    "tabs": "탭",
    "aglets": "애글리트",
    "drawstring": "드로스트링",
    "drawstrings": "드로스트링",
    "waistband": "웨이스트밴드",
    "waistline": "웨이스트라인",
    "waist": "웨이스트",
    "collar": "칼라",
    "collarless": "칼라리스",
    "cuffs": "커프스",
    "cuff": "커프스",
    "sleeves": "소매",
    "sleeve": "소매",
    "hood": "후드",
    "hem": "헴",
    "hems": "헴",
    "closure": "클로저",
    "closures": "클로저",
    "zip": "지퍼",
    "zipped": "지퍼",
    "zipper": "지퍼",
    "button": "버튼",
    "buttons": "버튼",
    "buttoned": "버튼",
    "snap": "스냅",
    "horn": "혼",
    "stud": "스터드",
    "studs": "스터드",
    "rivets": "리벳",
    "hook": "훅",
    "hooks": "훅",
    "flap": "플랩",
    "pockets": "포켓",
    "pocket": "포켓",
    "compartment": "수납공간",
    "compartments": "수납공간",
    "slot": "슬롯",
    "slots": "슬롯",
    "card": "카드",
    "cards": "카드",
    "bills": "지폐",
    "coin": "코인",
    "key": "키",
    "pouch": "파우치",
    "pouches": "파우치",
    "bag": "백",
    "shoulder": "숄더",
    "shoulders": "숄더",
    "back": "백",
    "front": "프론트",
    "side": "사이드",
    "sides": "사이드",
    "chest": "체스트",
    "inner": "이너",
    "interior": "인테리어",
    "external": "외부",
    "outer": "아우터",
    "removable": "탈부착",
    "adjustable": "조절 가능",
    "adjustment": "조절",
    "adjustement": "조절",
    "elasticated": "엘라스틱",
    "elastic": "엘라스틱",
    "padded": "패딩",
    "padding": "패딩",
    "pad": "패드",
    "pads": "패드",
    "trim": "트림",
    "piping": "파이핑",
    "bands": "밴드",
    "ribbon": "리본",
    "laces": "레이스",
    "lace": "레이스",
    "lacing": "레이싱",
    "tongue": "텅",
    "insole": "인솔",
    "outsole": "아웃솔",
    "sole": "솔",
    "soles": "솔",
    "heel": "힐",
    "heels": "힐",
    "toe": "토",
    "shoe": "슈즈",
    "shoes": "슈즈",
    "sneaker": "스니커즈",
    "lens": "렌즈",
    "lenses": "렌즈",
    "temples": "템플",
    "temple": "템플",
    "frame": "프레임",
    "bridge": "브릿지",
    "nose": "노즈",
    "visor": "바이저",
    "jacket": "재킷",
    "shirt": "셔츠",
    "jeans": "진",
    "scarf": "스카프",
    "necklace": "네크리스",
    "bracelets": "브레이슬릿",
    "jewel": "주얼",
    "jewels": "주얼",
    "charm": "참",
    "charms": "참",
    "fit": "핏",
    "fitted": "핏티드",
    "loose": "루즈",
    "classic": "클래식",
    "oversized": "오버사이즈",
    "cropped": "크롭",
    "crop": "크롭",
    "cut": "컷",
    "length": "기장",
    "maxi": "맥시",
    "midi": "미디",
    "mini": "미니",
    "wide": "와이드",
    "straight": "스트레이트",
    "slim": "슬림",
    "flare": "플레어",
    "flared": "플레어",
    "leg": "레그",
    "rise": "라이즈",
    "high": "하이",
    "mid": "미드",
    "low": "로우",
    "raw": "로우",
    "rounded": "라운드",
    "round": "라운드",
    "oval": "오벌",
    "flat": "플랫",
    "thin": "슬림",
    "soft": "소프트",
    "light": "라이트",
    "lightweight": "라이트웨이트",
    "natural": "내추럴",
    "contrasting": "컨트라스트",
    "tonal": "톤온톤",
    "gradient": "그라데이션",
    "graphic": "그래픽",
    "decorative": "장식",
    "central": "센터",
    "center": "센터",
    "middle": "미들",
    "main": "메인",
    "additional": "추가",
    "free": "프리",
    "covered": "커버",
    "open": "오픈",
    "hidden": "히든",
    "reversible": "리버시블",
    "virgin": "버진",
    "secondary": "보조",
    "material": "소재",
    "materials": "소재",
    "trimmings": "트리밍",
    "around": "",
    "first": "첫",
    "disc": "디스크",
    "disk": "디스크",
    "squared": "스퀘어",
    "rectangular": "사각",
    "tip": "팁",
    "bottom": "하단",
    "old": "올드",
    "western": "웨스턴",
    "framed": "프레임",
    "frame": "프레임",
    "helium": "헬륨",
    "edge": "엣지",
    "sweden": "스웨덴",
    "united": "영국",
    "kingdom": "",
    "uk": "UK",
    "hexagonal": "헥사곤",
    "design": "디자인",
    "inch": "인치",
    "rolled": "롤",
    "hand": "핸드",
    "ages": "에이징",
    "beautifully": "아름답게",
    "recommend": "권장",
    "avoid": "피하세요",
    "contact": "접촉",
    "oil": "오일",
    "perfume": "향수",
    "cosmetic": "화장품",
    "cosmetics": "화장품",
    "products": "제품",
    "come": "",
    "dabbed": "톡톡 두드려",
    "gently": "부드럽게",
    "absorbent": "흡수",
    "overexposure": "과다 노출",
    "heat": "열",
    "intense": "강한",
    "careful": "주의",
    "rub": "마찰",
    "against": "",
    "coarse": "거친",
    "abrasive": "마모성",
    "surfaces": "표면",
    "scratches": "스크래치",
    "diminished": "완화",
    "massaged": "마사지",
    "store": "보관",
    "protective": "보호용",
    "temperature": "온도",
    "humidity": "습도",
    "level": "수준",
    "unventilated": "밀폐",
    "area": "공간",
    "never": "절대",
    "plastic": "플라스틱",
    "srap": "스트랩",
    "bar": "바",
    "harry": "Harry",
    "harrys": "Harry's",
    "make": "",
    "sure": "",
    "long": "롱",
    "square": "스퀘어",
    "rounded": "라운드",
    "loop": "루프",
    "loops": "루프",
    "finishing": "마감",
    "finish": "마감",
    "made": "제작",
    "sweden": "스웨덴",
    "construction": "구조",
    "system": "시스템",
    "label": "라벨",
    "tag": "태그",
    "reference": "레퍼런스",
    "dimensions": "치수",
    "width": "너비",
    "height": "높이",
    "diameter": "직경",
    "drop": "드롭",
    "total": "전체",
    "minimum": "최소",
    "maximum": "최대",
    "carry": "캐리",
    "hand": "핸드",
    "elbow": "엘보",
    "neck": "넥",
    "neckline": "네크라인",
    "tie": "타이",
    "hood": "후드",
    "apron": "앞판",
    "gusset": "거싯",
    "vent": "벤트",
    "slit": "슬릿",
    "slits": "슬릿",
    "cut outs": "컷아웃",
    "cut-outs": "컷아웃",
    "cut out": "컷아웃",
    "frills": "프릴",
    "fringe": "프린지",
    "fringes": "프린지",
    "peplum": "페플럼",
    "cape": "케이프",
    "bra": "브라",
    "bustier": "뷔스티에",
    "stays": "스테이",
    "cups": "컵",
    "padding": "패딩",
    "down": "다운",
    "feather": "페더",
    "rubber": "러버",
    "water": "물",
    "cloth": "천",
    "made": "제작",
    "italy": "이탈리아",
    "portugal": "포르투갈",
    "france": "프랑스",
    "japan": "일본",
    "paris": "파리",
    "one": "1",
    "two": "2",
    "three": "3",
    "four": "4",
    "five": "5",
    "six": "6",
    "twelve": "12",
    "with": "",
    "and": "",
    "the": "",
    "a": "",
    "an": "",
    "of": "",
    "on": "",
    "at": "",
    "to": "",
    "for": "",
    "or": "",
    "in": "",
    "from": "",
    "by": "",
    "as": "",
    "is": "",
    "are": "",
    "be": "",
    "it": "",
    "its": "",
    "your": "",
    "you": "",
    "we": "",
    "our": "",
    "their": "",
    "them": "",
    "this": "",
    "that": "",
    "these": "",
    "those": "",
    "can": "",
    "may": "",
    "must": "",
    "should": "",
    "not": "",
    "do": "",
    "does": "",
    "if": "",
    "when": "",
    "over": "",
    "under": "",
    "into": "",
    "all": "",
    "any": "",
    "each": "",
    "some": "",
    "most": "",
    "more": "",
    "than": "",
    "thanks": "",
    "nickel": "니켈",
    "slip": "슬립",
    "uva": "UVA",
    "uvb": "UVB",
    "protects": "차단",
    "temple": "템플",
    "shape": "쉐입",
    "almond": "아몬드",
    "pointed": "포인티드",
    "note": "노트",
    "smoke": "스모크",
    "brown": "브라운",
    "cat": "캣",
    "eye": "아이",
    "stacked": "스택드",
    "pierced": "피어싱",
    "ears": "이어",
    "turn": "턴",
    "lock": "락",
    "polo": "폴로",
    "folded": "폴디드",
    "purse": "퍼스",
    "sliding": "슬라이딩",
    "knots": "노트",
    "eyelets": "아일렛",
    "memory": "메모리",
    "foam": "폼",
    "comfort": "컴포트",
    "support": "서포트",
    "better": "향상된",
    "perforated": "퍼포레이션",
    "perforations": "퍼포레이션",
    "flexible": "플렉서블",
    "hinge": "힌지",
    "crystals": "크리스탈",
    "resin": "레진",
    "tailored": "테일러드",
    "panel": "패널",
    "accessory": "액세서리",
    "rivets": "리벳",
    "mirror": "미러",
    "bullskin": "불스킨",
    "earring": "이어링",
    "dots": "닷",
    "inside": "인사이드",
    "right": "오른쪽",
    "left": "왼쪽",
    "fleece": "플리스",
    "upper": "갑피",
    "outs": "아웃",
    "aspect": "룩",
    "green": "그린",
    "computer": "노트북",
    "documents": "서류",
    "pleats": "주름",
    "pleat": "주름",
    "contrasted": "컨트라스트",
    "adorned": "장식",
    "backpack": "백팩",
    "fits": "수납",
    "drugstore": "드럭스토어",
    "claudine": "클로딘",
    "mock": "목",
    "carriage": "캐리지",
    "slingback": "슬링백",
    "slightly": "약하게",
    "conic": "코니컬",
    "holder": "홀더",
    "ties": "타이",
    "bevel": "베벨",
    "details": "디테일",
    "heel": "힐",
    "visor": "바이저",
    "side": "사이드",
    "evening": "이브닝",
    "clutches": "클러치",
    "clutch": "클러치",
    "nickel": "니켈",
}
# Keep as-is (units / codes). Matched case-insensitive as whole tokens.
KEEP_TOKENS = {
    "cm",
    "mm",
    "x",
    "xl",
    "xs",
    "xxl",
    "xxs",
    "s",
    "m",
    "l",
    "ct",
    "bc",
    "tpu",
    "n/a",
    "uk",
    "harry's",
    "daunou",
    "helium",
}


def normalize_key(s: str) -> str:
    s = (s or "").replace("\xa0", " ").replace("&amp;", "&")
    s = re.sub(r"Â", "", s)
    s = re.sub(r"([a-zA-Z])(\d)", r"\1 \2", s)
    s = re.sub(r"(\d)([a-zA-Z])", r"\1 \2", s)
    # Hyphenated words → spaces; keep numeric minus (-10°C)
    s = re.sub(r"(?<!\d)[-–—](?!\d)", " ", s.lower())
    s = re.sub(r"\s+", " ", s).strip(" .")
    s = s.lstrip("- ").strip()
    return s


def match_care_fit(s: str) -> str | None:
    key = normalize_key(s)
    if key in CARE_FIT_MAP:
        return CARE_FIT_MAP[key]
    if key in {"#n/a", "n/a"}:
        return ""
    # Prefix match for long shoe/belt/jewel/bag guides
    for en, ko in CARE_FIT_MAP.items():
        if len(en) >= 40 and key.startswith(en[:60]):
            return ko
    if "highest quality hides" in key and "shoes" in key:
        return CARE_FIT_MAP[
            "for your shoes, celine has selected the highest quality hides"
        ]
    if "celine belt was crafted" in key:
        return CARE_FIT_MAP["your celine belt was crafted using the most luxurious skins"]
    if "leather goods are crafted" in key:
        return CARE_FIT_MAP["celine leather goods are crafted in the most luxurious skins"]
    if "refined jewels" in key or "clean your jewel" in key:
        return CARE_FIT_MAP[
            "celine created high end and refined jewels with timeless materials"
        ]
    if "create your sunglasses" in key or "clean your sunglasses" in key:
        return CARE_FIT_MAP[
            "celine has selected materials of the highest quality to create your sunglasses"
        ]
    if "swimwear may only be returned" in key:
        return CARE_FIT_MAP[
            "swimwear may only be returned in new, unworn, & sellable condition. for hygiene purposes we advise trying on over your existing garments"
        ]
    return None


def prose_to_ko(text: str) -> str:
    """Local fashion-detail translator — whole phrases then words; never partial TITLE_MAP."""
    s = (text or "").replace("\xa0", " ").replace("&amp;", "&")
    s = re.sub(r"Â", "", s)
    s = re.sub(r"([a-zA-Z])(\d)", r"\1 \2", s)
    s = re.sub(r"(\d)([a-zA-Z])", r"\1 \2", s)
    s = re.sub(r"([a-z])([A-Z])", r"\1 \2", s)  # pocketsRivets / camel glue
    s = re.sub(r"(?i)(pockets)(rivets|interior)", r"\1 \2", s)
    s = re.sub(r"(?i)(cut)(outs)", r"\1 \2", s)
    # Fix glued sentences: "230°FDo not" / ".Only use"
    s = re.sub(r"([.!?]|°[CF]|°c|°f)([A-Z])", r"\1 \2", s)
    s = s.strip()
    if not s:
        return ""

    hit = match_care_fit(s)
    if hit is not None:
        return hit

    # Apply key multi-word phrases before dimension short-circuit
    out_pre = re.sub(r"(?<!\d)[-–—](?!\d)", " ", s)
    for en, ko in sorted(PROSE_PHRASES.items(), key=lambda kv: -len(kv[0])):
        if len(en) < 8:
            continue
        out_pre = re.sub(rf"(?i)\b{re.escape(en)}\b", ko, out_pre)
    s = out_pre

    # Glued multi-sentence care blobs (often missing newlines in scrape)
    if len(s) > 80 and s.count(".") >= 2 and re.search(
        r"(?i)(wash|dry|iron|steam|bleach|clean|water)", s
    ):
        parts = [p.strip() for p in re.split(r"(?<=[.!?])\s*", s) if p.strip()]
        if len(parts) >= 2:
            outs = []
            for p in parts:
                h = match_care_fit(p)
                outs.append(h if h is not None else prose_to_ko(p))
            joined = " ".join(x for x in outs if x)
            if joined and is_good_korean(joined):
                return joined

    # Dimension / measure lines: keep structure, translate labels
    if re.search(r"\d", s) and re.search(
        r"(?i)\b(WIDTH|HEIGHT|DROP|DIAMETER|LENGTH|MINIMUM|MAXIMUM|TEMPLE|LENS|BRIDGE|HANDLE|HANDLES|HEEL|VISOR|RING|CM|IN|MM|너비|기장|드롭|템플|렌즈|브릿지|핸들|힐|바이저|링)\b",
        s,
    ):
        out = re.sub(r"(?<!\d)[-–—](?!\d)", " ", s)
        for en, ko in sorted(
            {
                **{
                    k: v
                    for k, v in PROSE_PHRASES.items()
                    if any(x in k for x in ("strap", "handle", "drop", "temple", "lens", "nose", "bridge"))
                },
                "removable and adjustable leather strap": "탈부착·조절 가능 레더 스트랩",
                "removable and adjustable strap": "탈부착·조절 가능 스트랩",
                "adjustable and removable leather strap": "조절·탈부착 레더 스트랩",
                "adjustable leather strap": "조절 가능 레더 스트랩",
                "adjustable strap": "조절 가능 스트랩",
                "removable leather handle": "탈부착 레더 핸들",
                "leather handle": "레더 핸들",
                "leather handles": "레더 핸들",
                "two handles": "핸들 2개",
                "two leather handles": "레더 핸들 2개",
                "leather strap": "레더 스트랩",
                "minimum drop": "최소 드롭",
                "maximum drop": "최대 드롭",
                "temple length": "템플 기장",
                "nose bridge width": "노즈 브릿지 너비",
                "nose bridge": "노즈 브릿지",
                "lens width": "렌즈 너비",
                "adapted to a mobile phone with a maximum size of": "최대 휴대폰 크기",
                "TEMPLE": "템플",
                "LENS": "렌즈",
                "NOSE": "노즈",
                "BRIDGE": "브릿지",
                "HANDLE": "핸들",
                "HANDLES": "핸들",
                "WIDTH": "너비",
                "HEIGHT": "높이",
                "DROP": "드롭",
                "DIAMETER": "직경",
                "LENGTH": "기장",
                "MINIMUM": "최소",
                "MAXIMUM": "최대",
                "TOTAL": "전체",
                "INCH": "인치",
            }.items(),
            key=lambda kv: -len(kv[0]),
        ):
            out = re.sub(rf"(?i)\b{re.escape(en)}\b", ko, out)
        out = re.sub(r"(?i)\bwith\b", "", out)
        out = re.sub(r"(?i)\band\b", "", out)
        out = re.sub(r"(?i)\ba\b", "", out)
        out = re.sub(r"(?i)\bthe\b", "", out)
        out = re.sub(r"(?i)\bon the side\b", "측면", out)
        out = re.sub(r"(?i)\bin\b", "IN", out)
        # Prefer metric when both IN and CM are present
        out = re.sub(
            r"(?i)\b\d+(?:\.\d+)?\s*IN\s*\((\d+(?:\.\d+)?)\s*CM\)",
            r"\1cm",
            out,
        )
        out = re.sub(
            r"(?i)\b[\d.]+\s*(?:[x×]\s*[\d.]+\s*){1,2}IN\s*\(([^)]*?)\s*CM\)",
            r"\1cm",
            out,
        )
        return re.sub(r"\s+", " ", out).strip(" ,")

    # Normalize hyphenated compounds so phrase/word maps hit (mid-rise, celine-engraved).
    out = re.sub(r"(?<!\d)[-–—](?!\d)", " ", s)

    # Phrases longest-first
    for en, ko in sorted(PROSE_PHRASES.items(), key=lambda kv: -len(kv[0])):
        out = re.sub(rf"(?i)\b{re.escape(en)}\b", ko, out)

    def repl_word(m: re.Match[str]) -> str:
        w = m.group(0)
        low = w.lower()
        if low in KEEP_TOKENS:
            return w
        if low in PROSE_WORDS:
            return PROSE_WORDS[low]
        if len(low) <= 2 and low.isalpha():
            return w
        return w

    out = re.sub(r"[A-Za-z][A-Za-z'-]*", repl_word, out)
    out = re.sub(r"\s+", " ", out).strip(" ·,;/")
    out = re.sub(r"\s+,", ",", out)
    out = re.sub(r"\s+\.", ".", out)
    out = re.sub(r"\s{2,}", " ", out).strip()
    return out
