#!/usr/bin/env python3
"""Curated Korean for Dior men's small leather goods characteristics."""
from __future__ import annotations

FEATURE_KO: dict[str, str] = {
    "Dust bag included": "더스트백 포함",
    "Made in Italy": "이탈리아 제조",
    "Embossed Dior signature on the interior": "내부에 엠보싱 처리된 디올 시그니처",
    "Embossed Dior clover signature on the interior": "내부에 엠보싱 처리된 디올 클로버 시그니처",
    "Main composition: calfskin": "주성분: 카프스킨",
    "Main composition: lambskin": "주성분: 송아지 가죽",
    "Main composition: cotton canvas and technical fabric": "주성분: 면 캔버스 및 테크니컬 패브릭",
    "Main composition: cotton, technical fabric and calfskin": "주요 구성: 면, 테크니컬 패브릭 및 카프스킨",
    "Main composition: calfskin, cotton and technical fabric": "주요 구성: 카프스킨, 면 및 테크니컬 패브릭",
    "Main composition: cotton and lambskin": "주요 구성: 면 및 송아지 가죽",
    "Main composition: cotton, lambskin and technical fabric": "주요 구성: 면, 송아지 가죽 및 테크니컬 패브릭",
    "Calfskin and technical fabric lining": "카프스킨 및 테크니컬 패브릭 안감",
    "Technical fabric and calfskin lining": "테크니컬 패브릭 및 카프스킨 안감",
    "Technical fabric, cotton and calfskin lining": "테크니컬 패브릭, 면 및 카프스킨 안감",
    "Cotton and calfskin lining": "면 및 카프스킨 안감",
    "Cotton, calfskin and technical fabric lining": "면, 카프스킨 및 테크니컬 패브릭 안감",
    "Cotton, linen and calfskin lining": "면, 리넨 및 카프스킨 안감",
    "Calfskin lining": "카프스킨 안감",
    "Ruthenium-finish brass Dior signature on the front": "전면 루테늄 마감 황동 디올 시그니처",
    "Palladium-finish brass CD Icon signature on the front": "전면 팔라듐 마감 황동 CD Icon 시그니처",
    "Hot-stamped Dior signature on the front": "전면 핫스탬프 디올 시그니처",
    "Embossed Dior signature on the front": "전면 엠보싱 디올 시그니처",
    "Dior signature on the front": "전면의 디올 시그니처",
    "Six card slots": "카드 슬롯 6개",
    "Four card slots": "카드 슬롯 4개",
    "Eight card slots": "카드 슬롯 8개",
    "Three card slots": "카드 슬롯 3개",
    "Three front card slots": "앞면 카드 슬롯 3개",
    "Three rear card slots": "뒷면 카드 슬롯 3개",
    "Central card slot": "중앙 카드 슬롯",
    "Card slot": "카드 슬롯",
    "Two slip pockets for receipts": "영수증용 슬립 포켓 2개",
    "Interior slip pocket": "내부 슬립 포켓",
    "Interior slip pockets": "내부 슬립 포켓",
    "Rear slip pocket": "리어 슬립 포켓",
    "Two interior slip pockets": "내부 슬립 포켓 2개",
    "Interior zipped pocket": "내부 지퍼 포켓",
    "Main zipped compartment": "메인 지퍼 수납 공간",
    "Two flat compartments": "플랫 수납 공간 2개",
    "Two bill compartments": "지폐 수납 공간 2개",
    "Space for boarding pass": "보딩패스 수납 공간",
    "Removable leather wrist strap": "탈착식 가죽 손목 스트랩",
    "D-ring for attaching accessories": "액세서리 부착용 D-링",
    "Leather cord": "가죽 코드",
    "Split ring": "스플릿 링",
    "Magnetic phone stand": "마그네틱 폰 스탠드",
    "Tape measure detail": "줄자 디테일",
    "Technical fabric, cotton and calfskin lining": "테크니컬 패브릭, 면 및 카프스킨 안감",
    "Ruthenium-finish brass CD Icon signature on the front": "전면 루테늄 마감 황동 CD Icon 시그니처",
    "Gold-finish brass CD Icon signature on the front": "전면 골드 마감 황동 CD Icon 시그니처",
    "Silver-finish brass CD Icon signature on the front": "전면 실버 마감 황동 CD Icon 시그니처",
    "Zipped closure": "지퍼 클로저",
    "Snap closure": "스냅 클로저",
    "Magnetic closure": "마그네틱 클로저",
    "Button closure": "단추 클로저",
    "Interior flat pocket": "내부 플랫 포켓",
    "Interior flat pockets": "내부 플랫 포켓",
    "Coin pocket": "코인 포켓",
    "ID window": "신분증 창",
    "Business card slots": "명함 슬롯",
    "A5 format": "A5 포맷",
    "A4 format": "A4 포맷",
    # Men's accessories & shoes (GB PLP characteristics)
    "Tonal Dior signature adjustment tab in the back": "뒷면 톤온톤 디올 시그니처 조절 탭",
    "Grosgrain Dior signature on the interior": "내부 그로그레인 디올 시그니처",
    "White rubber Avenue Montaigne signature": "화이트 러버 Avenue Montaigne 시그니처",
    "DIOR AND RIMOWA signature metallic plate": "DIOR AND RIMOWA 시그니처 메탈릭 플레이트",
    "CD signature Multiwheel® system": "CD 시그니처 Multiwheel® 시스템",
    "Tonal Dior Moulures jacquard motif": "톤온톤 Dior Moulures 자카드 모티프",
    "Red jacquard Dior Colibri": "레드 자카드 Dior Colibri",
    "Allover Toile de Jouy Sauvage jacquard motif": "올오버 Toile de Jouy Sauvage 자카드 모티프",
    "Couture Charms articulated bee": "Couture Charms 관절형 벌",
    "Green resin Dior Trèfle details": "그린 레진 Dior Trèfle 디테일",
    "Crystal and silver metal temples with white 'Christian Dior' logo": "크리스탈 & 실버 메탈 템플, 화이트 'Christian Dior' 로고",
    "Frame in black acetate covered in Swarovski®* crystals": "Swarovski®* 크리스탈을 입힌 블랙 아세테이트 프레임",
    "Temple adorned with a 'Christian Dior' signature scratch detail": "템플에 'Christian Dior' 시그니처 스크래치 디테일",
}

# Fix typo in one entry
FEATURE_KO["Two slip pockets for receipts"] = "영수증용 슬립 포켓 2개"

MATERIAL_KO: dict[str, str] = {
    "calfskin": "카프스킨",
    "lambskin": "램스킨",
    "grained calfskin": "그레인 카프스킨",
    "smooth calfskin": "스무스 카프스킨",
    "technical fabric": "테크니컬 패브릭",
    "cotton canvas": "면 캔버스",
    "Dior Gravity leather": "Dior Gravity 레더",
    "Dior Oblique jacquard": "Dior Oblique 자카드",
    "Smooth leather": "스무스 레더",
    "Grained leather": "그레인 레더",
    "Printed leather": "프린트 레더",
    "Patent leather": "페이턴트 레더",
    "Metallic leather": "메탈릭 레더",
    "Jacquard": "자카드",
    "Raffia": "라피아",
    "Silver": "실버",
    "Brass": "황동",
    "Acetate": "아세테이트",
    "Canvas": "캔버스",
    "Metal": "메탈",
    "Resin": "레진",
    "Non Applicable": "해당 없음",
    "Palladium finish": "팔라듐 마감",
    "Aluminum": "알루미늄",
    "PVC": "PVC",
    "Polyester": "폴리에스터",
    "Rubber": "고무",
    "Cotton": "면",
    "Silk": "실크",
    "Wool": "울",
    "Leather": "가죽",
    "LEATHER + BRASS": "가죽 + 황동",
    "ECHARPE 142x142 FR IMP RAY": "140×140 스카프",
}

MADEIN_KO: dict[str, str] = {
    "DE": "독일",
    "IT": "이탈리아",
    "FR": "프랑스",
    "PT": "포르투갈",
    "GB": "영국",
    "UK": "영국",
    "JP": "일본",
    "CN": "중국",
}
