/* Auto-generated by scripts/build-mb-catalog.py — do not edit */
import type { Product } from "@/data/product-types";
import data from "./mb-catalog.json";

/** Mulberry catalog (JSON import keeps the TS module small for Vercel builds). */
export const mbCatalogProducts = data as unknown as Product[];
