/* Auto-generated by scripts/build-bv-catalog.py — do not edit */
import type { Product } from "@/data/product-types";
import data from "./bv-catalog.json";

/** Bottega Veneta catalog (JSON import). */
export const bvCatalogProducts = data as unknown as Product[];
